# -*- coding: utf-8 -*-
"""Generated by ArcGIS ModelBuilder on: 2020-01-27 14:38:51
All ModelBuilder functionality may not be exported. Edits may be required for equivalency with the original model.
"""

import arcpy

# To allow overwriting the outputs change the overwrite option to true.
arcpy.env.overwriteOutput = False

# Load required toolboxes
arcpy.ImportToolbox("Model Tools")

# Local variables:
各类球类场所步行15分钟 = r"D:\Desktop\南昌市健康资源分析\固定时段服务区.gdb\公共康体保健\各类球类场所步行15分钟"


# Process: 如果字段已存在
arcpy.FieldExistsIfThenElse_mb(in_table=各类球类场所步行15分钟, field_test_type="MUST_HAVE_AT_LEAST_ONE_FIELD", field="name")
print(result)